### PR TITLE
Import Qt quick controls2 gallery example

### PR DESCRIPTION
**Pull request by tones111**
This example doesn't show any new technical capabilities beyond what th existing hello world shows, but it does provide examples of many of the available controls.  The only modifications from the Qt example files are replacing the c++ main file with the basic hello world c file and removing the qrc references from the config files.

### CODE REVIEW

**Comment by florianjacob** [comment]
Thanks. :+1: 

What I see that could be improved:
* [ ] Add screenshots of the running example
* [ ] Write a comment in the main c file in which you explain what the example does and is intended to show, similar to what you wrote here.
* [ ] In that coment, link back to the original example (https://doc-snapshots.qt.io/qt5-5.7/qtquickcontrols2-gallery-example.html , I think?)

Regarding qrc files, I think we could actually support them, in qmake based projects by using qmake facilities, but even in external projects not using qmake, by using `rcc <resource file>.qrc` and compiling the resulting C code:
http://doc.qt.io/qt-5/resources.html#resource-collection-files-op-op-qrc

But I don't know whether they're actually that useful. @seanchas116, what do you think?

**Comment by tones111** [comment]
Thanks for the tip about qrc support.  I had given up after being unable to load, but it turns out that adding support was pretty easy.  I've updated the comments as suggested (I think), but am not really sure what you're looking for for the screenshots.

**Comment by florianjacob** [comment]
Regarding the screenshot: Just fire up the example and do a screenshot in a representative kind of way, so that the user knows what to expect even before he managed to run the code. :wink: fizzbuzz example: https://github.com/seanchas116/libqmlbind/blob/master/examples/fizzbuzz/screenshot.png

By the way, is there a reason that you nested the example in `qtquickcontrols2/controls/gallery` instead of e.g. directly in `qtquickcontrols2_gallery`?

The comment is nice, but could you add a note that the example needs Qt >=5.7 to run? (which is why I can't try it myself, I'm on Qt 5.6).

In general: Thanks that you figured out how to use qrc files, very nice! :+1:  @seanchas116 what's your opinion on this? Could / should we unify `load_path` and `load_url`?

**Comment by tones111** [comment]
Screenshots added.  While the url in the main file refers to v5.7 (5.6 results in a 404 error) this example builds and runs fine on 5.6.  You may need to have the relevant package installed.  On my Arch system that is qt5-quickcontrols2.

**Comment by florianjacob** [comment]
Oh, I thought it wouldn't be possible to backport qt5-quickcontrols2 to older Qt versions than 5.7. Just installed the qt5-quickcontrols2 package and was able to run it myself. Cool stuff! :+1:

Now looking again at the API changes with some distance, I think they're fine and we don't need to unify the loading methods, at least not until we don't  get a third variant or something.

Sorry for the long wait, I was quite busy the last month. Thanks for getting into such a nice shape, I'll merge it now. :shipit: :sparkles:

**Pull request merged**
