### PR TITLE
Interface cleanup

### PR DESCRIPTION
**Pull request by florianjacob**
Apply interface cleanups discussed in #9

### CODE REVIEW

**Comment by florianjacob** [comment]
Initially, I wanted to ask whether it's ok to fix the tests that way by getting the indexes later directly via the metaobject, as I thought that that part of the test got a little trivial through the change.

But it seems like it still is a good sanity check because it fails and no methods of the provided name exist. :laughing: @seanchas116, do you have any idea what's going on there?

**Comment by seanchas116** [comment]
Looks like specifying method signature in `indexOfMethod` fixes tests. (libqmlbind always uses `QJSValue` as parameter types)

For example:

`metaobj->indexOfMethod("incrementBy");` → `metaobj->indexOfMethod("incrementBy(QJSValue)");`
`metaobj->indexOfMethod("valueChanged");` → `metaobj->indexOfMethod("valueChanged(QJSValue)");`

**Comment by florianjacob** [comment]
Thanks! Now I also understand the why & how of the `methodSignature(…)` function in the exporter.

**Comment by seanchas116** [comment]
Now that tests are fixed, can I merge this pull request now? (maybe this pr helps #9)

**Comment by florianjacob** [comment]
Yes, let's get this merged. :+1:

**Comment by seanchas116** [comment]
Okay, merging...

**Pull request merged**
